#!/bin/sh

DISPLAY=":0"
WORKTIME=0
PAUSETIME=0
LONGTIME=0
MODE=""

zinfo() {
  zenity \
    --info \
    --title=" zomo" \
    --width=300 \
    --height=75 \
    --text="$(date +%H:%M) - $1"
}

work() {
  sleep $(($1 * 60)) \
  && zinfo "Take a break"
}

pause() {
  sleep $(($1 * 60)) \
  && zinfo "Back to work"
}

main() {
  if [ "$1" = "-h" ] || [ $# -eq 0 ]; then
    printf "USAGE: zomo <MODE> [OPTIONS]\n"
    printf "\n"
    printf "MODES:\n"
    printf "\twork     - work cycle. default: 25 min\n"
    printf "\tpause    - pause cycle. default: 5 min\n"
    printf "\tlong     - long pause cycle. default: 15 min\n"
    printf "\tfull     - four pomodoro cycles ended by a long pause\n"
    printf "\tinfinite - endless full mode\n"
    printf "\n"
    printf "OPTIONS:\n"
    printf "\t-wd - work duration\n"
    printf "\t-pd - pause duration\n"
    printf "\t-ld - long duration\n"

    return
  elif [ "$1" = "status" ]; then
    if [ -e $HOME/.zomo.lock ]; then
      echo "Already running."
    else
      echo "Not running"
    fi
  elif [ "$1" = "kill" ]; then
    kill "$(cat $HOME/.zomo.lock)"
  fi

  printf "%i" $$ > $HOME/.zomo.lock

  MODE=$1
  shift

  while true; do
    case $1 in
      "-wd")
        WORKTIME=$2
        ;;
      "-pd")
        PAUSETIME=$2
        ;;
      "-ld")
        LONGTIME=$2
        ;;
      *)
        break
        ;;
    esac
    shift 2
  done

  case $MODE in
    "work")
      work $WORKTIME
      ;;
    "pause")
      pause $PAUSETIME
      ;;
    "long")
      pause $LONGTIME
      ;;
    "full")
      for i in $(seq 4); do
        work $WORKTIME
        pause $PAUSETIME
      done
      pause $LONGTIME
      ;;
    "infinite")
      while true; do
        for i in $(seq 4); do
          work $WORKTIME
          pause $PAUSETIME
        done
        pause $LONGTIME
      done
      ;;
  esac

  rm $HOME/.zomo.lock
}

main $@
