#!/bin/sh

DISPLAY=":0"
WORKTIME=25 # Default work duration period:        25 min
PAUSETIME=5 # Default pause duration period:        5 min
LONGTIME=15 # Default long pause duration period : 15 min
MODE=""

timer() {
  TIME_ELAPSED=0
  ACTUAL_CYCLE="$2"
  while [ $TIME_ELAPSED -lt $1 ]; do
    sleep 1
    TIME_ELAPSED=$((TIME_ELAPSED + 1))
    echo "$$ $TIME_ELAPSED $ACTUAL_CYCLE" > /tmp/zomo.lock
  done
  rm /tmp/zomo.lock
}

zinfo() {
  zenity \
    --info \
    --title=" zomo" \
    --width=300 \
    --height=75 \
    --text="$(date +%H:%M) - $1"
}

work() {
  timer $(($1 * 60)) work \
  && zinfo "Take a break"
}

pause() {
  timer $(($1 * 60)) pause \
  && zinfo "Back to work"
}

show_usage() {
  printf "USAGE: zomo <MODE> [OPTIONS]\n"
  printf "\n"
  printf "MODES:\n"
  printf "\twork     - work cycle. default: 25 min.\n"
  printf "\tpause    - pause cycle. default: 5 min.\n"
  printf "\tlong     - long pause cycle. default: 15 min.\n"
  printf "\tfull     - four pomodoro cycles ended by a long pause.\n"
  printf "\tinfinite - endless full mode.\n"
  printf "\tstatus   - displays current time status.\n"
  printf "\tkill     - terminates the current timer cycle.\n"
  printf "\n"
  printf "OPTIONS:\n"
  printf "\t-wd - work duration  (in minutes).\n"
  printf "\t-pd - pause duration (in minutes).\n"
  printf "\t-ld - long duration  (in minutes).\n"
  exit 0
}

show_status() {
  {
    exec 2> /dev/null;
    kill -0 "-$(awk '{print $1}' /tmp/zomo.lock)";
  }
  if [ $? -eq 0 ]; then
    ELAPSED=$(awk '{print $2}' /tmp/zomo.lock)
    TYPE=$(awk '{print $3}' /tmp/zomo.lock)
    echo "Already running on a $TYPE cycle."
    echo "Time elapsed: $((ELAPSED/60))m $((ELAPSED % 60))s"
  else
    echo "Not running"
  fi

  exit 0
}

kill_proc() {
  {
    exec 2> /dev/null;
    kill -- "-$(awk '{print $1}' /tmp/zomo.lock)";
  }
  if [ $? -eq 0 ]; then
    echo "Killed"
  else
    echo "Not running"
  fi
  rm /tmp/zomo.lock 2> /dev/null

  exit 0
}

main() {

  MODE=$1
  shift

  while true; do
    case $1 in
      "-wd")
        WORKTIME=$2
        ;;
      "-pd")
        PAUSETIME=$2
        ;;
      "-ld")
        LONGTIME=$2
        ;;
      *)
        break
        ;;
    esac
    shift 2
  done

  case $MODE in
    "work")
      work $WORKTIME
      ;;
    "pause")
      pause $PAUSETIME
      ;;
    "long")
      pause $LONGTIME
      ;;
    "full")
      for i in $(seq 3); do
        work $WORKTIME
        pause $PAUSETIME
      done
      work $WORKTIME
      pause $LONGTIME
      ;;
    "infinite")
      while true; do
        for i in $(seq 3); do
          work $WORKTIME
          pause $PAUSETIME
        done
        work $WORKTIME
        pause $LONGTIME
      done
      ;;
  esac
}

if [ "$1" = "-h" ] || [ $# -eq 0 ]; then
  show_usage
elif [ "$1" = "status" ]; then
  show_status
elif [ "$1" = "kill" ]; then
  kill_proc
fi

( main $@ ) &
